######################################################################
# Automatically generated by qmake (3.0) Thu Dec 8 18:00:51 2016
######################################################################

TEMPLATE = app
TARGET = Part2
INCLUDEPATH += .

# Input
SOURCES += convolve.cpp
           #fileTester.cpp \
           #outWrite.c \
           #pow2.cpp \
           #test.c \
           #test.cpp \
           #testtone.c
